### ISSUE TITLE
Welcome screen: image moves as text is typed

### ISSUE THREAD

**Issue by LennardVaarten** [janmechtel/shortcutsensei#17]
video:
https://user-images.githubusercontent.com/73364073/141683259-e51184bc-09a8-414a-9d3a-c3af98fb04e3.mp4

I tried to position the image to the right from the start, but wasn't sure how since we're not working with a .css file anymore.

**Comment by LennardVaarten** [comment]
Also, we might wanna make the cursor disappear after it completes typing?

Found this, but not sure how to implement in our code: https://codepen.io/alexmacarthur/pen/WzVqeM

**Comment by janmechtel** [comment]
Great find. Just put it into `onboarding.ts`:
new TypeIt("#typeit", {
	waitUntilVisible: true,
	speed: 30, 
  	afterComplete: function (step, instance) {
		instance.destroy();
  	}
})
