### ISSUE TITLE
Gmail: Remove the TODOS: to bring the shortcuts in line

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/shortcutsensei#30]
Add the beginning of the clickhandler we have a special case for Ctrl+K shortcut. I'd like to remove the special case from there.

```
//TODO: this should go elsewhere into the normal list from above!
	if (outerHTML.includes("hidden;\">Invalid email address") && outerHTML.length > 10000) {
		showKeyPopup(`CTRL+K`, `Link to`);
		return;
	} else {
```

**Comment by janmechtel** [comment]
@LennardVaarten do you remember why the special case was introduced (`&& outerHTML.length > 10000`)? 

Will the notification give a false positive otherwise? On which button, maybe we can find a different way

**Comment by LennardVaarten** [comment]
It's a very hacky solution, but I did it because the outerHTML for the "Link to" button was incredibly long and had things in common with several other buttons and with the outerHTML of non-button areas on the screen. I can later check out what false positives it gave exactly

**Comment by janmechtel** [comment]
Ok, I did what i could. It's still not pretty but ...
