### ISSUE TITLE
Popup Icon is hard to see

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/shortcutsensei#32]
![image](https://user-images.githubusercontent.com/1004314/141816890-55b6c09c-685d-43fa-8430-11566d2b7165.png)
Is there a way to make it bigger? maybe with less margin?

Maybe cut off the laptop at the bottom so to make the head bigger? We can also try to fill background completely with light green or remove the circle, so we can focus more on the head/body?

**Comment by LennardVaarten** [comment]
i don't know, the icon i uploaded has very little margin to begin with. could it be something firefox does?

i'll try your suggestion of making the whole background light green and zooming in on the head(/body)

**Comment by janmechtel** [comment]
![image](https://user-images.githubusercontent.com/1004314/142502344-3af5bbce-f755-465c-946f-ea4602d1697a.png)

Not sure if this is any better?

**Comment by janmechtel** [comment]
@LennardVaarten I like this one, what do you think:

![image](https://user-images.githubusercontent.com/1004314/142502534-a61a1af4-ccb4-4ee7-8ac8-2506bb8e5fee.png)
