### ISSUE TITLE
Image on welcome screen again moves with text

### ISSUE THREAD

**Issue by LennardVaarten** [janmechtel/shortcutsensei#35]
Did something move the image to the left? despite the line breaks, it 'moves out of the way' of the text again

**Comment by janmechtel** [comment]
On my screen I can't observe it :-/ Please share a recording.

I guess you could either fix it by changing text length/introducing more breaks or try to set a width in `onboarding.html`
- `<div class="relative py-3 sm:max-w-4xl sm:mx-auto">` increase the `max-w-4x` ? remove the `max-`?
-`<div class="flex-initial h-96">` add w-64 here?
- ...


change this to

**Comment by janmechtel** [comment]
![goAKCwlaHf](https://user-images.githubusercontent.com/1004314/141856796-26be5e3c-ea31-44df-b7cd-3e60095dd04c.gif)

**Comment by LennardVaarten** [comment]
https://user-images.githubusercontent.com/73364073/141957476-c7dcf867-4f20-4609-b511-07968f2db77f.mp4

This is what it looked like for me. Fixed now, check the pull request
