### ISSUE TITLE
Notification with multiple interactions (controls)

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/shortcutsensei#40]
At the moment, we only have one clickhandler for the entire notification.

This one is mostly (and should?) only be used for closing it.

There are several other interactions that might be helpful:
1. #41
1. Open #39
1. #42

Later:
1. #43
1. #44

# Options

1. Get a new notification library (AltertifyJS)
1. build our own (flexibility, not THAT hard?, but hard)
1. Extend the one we have

![image](https://user-images.githubusercontent.com/1004314/142062979-ae3e3dc8-f995-4342-a583-71554e3b2eea.png)

Branch Version
![image](https://user-images.githubusercontent.com/1004314/149411244-001e5c55-126c-4cb8-9aa5-d32cc2b69d68.png)

Current Version
![image](https://user-images.githubusercontent.com/1004314/149411587-597014fd-04ae-4b92-a084-0643d1aff82c.png)

**Comment by LennardVaarten** [comment]
- Make branch version more like published version 
--> either gears icon with drop-down window
--> or icons with tooltips, aligned with X button
