### ISSUE TITLE
Snooze all notifications for a while

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/shortcutsensei#41]
Would be nice to pause all notifications for a while if you are busy / presenting or for whatever reason.

# For How long should we snooze?

- I feel like 24 hours might be easiest? 
- Or maybe 2 hours is enough?

**Comment by janmechtel** [comment]
@LennardVaarten what do you think, for how long should we snooze?

**Comment by janmechtel** [comment]
Looking into this I was wondering what's the cost for doing OptionsSymc.getall(), because it seemed like a lot, if I only need a couple.

It seems that it's using browser.storage under the hood.

Also I've discovered this list: https://github.com/fregante/webext-fun

What could be interesting
- options per domain
- https://github.com/fregante/webext-domain-permission-toggle

**Comment by LennardVaarten** [comment]
@janmechtel 24 hours seems good to me, better to have it be on the long side, rather than so short that users will get annoyed.

domain permission toggle looks great!

**Comment by janmechtel** [comment]
Actually snooze length can be an option :-) I'll default that one to 24 hours

**Comment by janmechtel** [comment]
https://github.com/janmechtel/shortcutsensei/commit/e344b00799e212b4c8f58a1ab41b40ca46b3cd58
