### ISSUE TITLE
Don't show this shortcut again

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/shortcutsensei#42]
If a shortcut is broken or unhelpful to you, users should have the option to disable it.

**Comment by janmechtel** [comment]
@LennardVaarten to store this information (per shortcut) is actually leading the way towards holding the shortcut database in storage and not in the code.

Because otherwise we'd have it in 2 places:
1. Code = shortcut definitions etc.
2. (Options) Storage = setting whether a shortcut is snoozed or not ...

**Comment by janmechtel** [comment]
To start simple we could store a list of "snoozed" shortcuts as an option.

# ID

For this shortcuts should get an id?

Or can we use application + shortcut keys? Which fails if we ever edit the shortcut key or a shortcut. So I think id is important.

# Migrations

Would also be good to think about migrations, when we have a database where we make changes to the keys, descriptions or exemptions... As long as we have a numeric id that should be fine.

**Comment by janmechtel** [comment]
Should the extension load the initial list of shortcuts from the code or from a server?

- backend/server would mean we could deploy/test new shortcuts without releasing the extension, but this can also be achieved by importing the shortcuts I guess. + I would require a backend + software could fail if backend is down?

**Comment by LennardVaarten** [comment]
I like the idea of an ID (pun not intended). 
Actually, maybe the ID should be something informative instead of just a code/number, so that we can make it easy for users to see which shortcuts they've disabled and then re-enable them. So IDs like:

Gmail - Archive Email (E)
Gmail - Mark as Read (Shift+I)
Github - ____________ (___)
....

We would then have to make it a habit to also change the ID whenever we change the shortcut / shortcut keys (I'm not sure how often that would happen).
Or do you think this would make it too difficult for us?

**Comment by LennardVaarten** [comment]
About the server, I'm probably not as informed on the pros and cons as you are, but sounds like giving up some robustness for not much benefit? And has anything been stopping us so far from testing new shortcuts without releasing the extension?

**Comment by janmechtel** [comment]
Thanks, I've introduced an id, the purpose is precisely that there should be no reason to ever change it.

Let's say the user disabled a shortcut, when we change the string id/label/name, then we'd loose the setting and the user would have to disable again. With a numeric id it's easier for us to prevent.

For now I made this a simple feature where you can go into options and provide ids that you want to be disabled.

Later we can link this up with code from the notification that can "add the current shortcuts id to the list"

**Comment by LennardVaarten** [comment]
Yeah fair. Though I was just thinking, let's say we have IDs 1-43 for Gmail and 44-XX for Github; wouldn't things get messy if we then want to add a new shortcut to Gmail? If so, would it be better to make the IDs something like GM1, GM2, GM3... for Gmail?
